// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1d_V13Jk8qflgd52GKkqOEf_4prUqV-k',
    appId: '1:1010994691811:web:5131c65b45f57e1aaf8fd6',
    messagingSenderId: '1010994691811',
    projectId: 'genupathlabs-28005',
    authDomain: 'genupathlabs-28005.firebaseapp.com',
    databaseURL: 'https://genupathlabs-28005.firebaseio.com',
    storageBucket: 'genupathlabs-28005.appspot.com',
    measurementId: 'G-6R0RHRH1Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD52PFU-VnaS2Lnsn9qYGNADSWuz13RtwQ',
    appId: '1:1010994691811:android:ca2fcc39b04831cd',
    messagingSenderId: '1010994691811',
    projectId: 'genupathlabs-28005',
    databaseURL: 'https://genupathlabs-28005.firebaseio.com',
    storageBucket: 'genupathlabs-28005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyevA3w9TN18VVJ4bnFTryGYTS00bsKIk',
    appId: '1:1010994691811:ios:0e88f87215df73e1af8fd6',
    messagingSenderId: '1010994691811',
    projectId: 'genupathlabs-28005',
    databaseURL: 'https://genupathlabs-28005.firebaseio.com',
    storageBucket: 'genupathlabs-28005.appspot.com',
    iosBundleId: 'com.genupathlabs.genu',
  );
}
